### PR TITLE
Allow props to derive state upstream

### PR DESCRIPTION
**Pull request by thevaleriemack**
### What does this PR do?
Allows a widget to utilize carousel component props to derive state of an upstream component.

### Where should the reviewer start?
index.js

### Background context:
I made this mod because I wanted to detect when the carousel was at the last frame. In my use case, I enable a button once the user has advanced to the last frame, and I disable the button if they move to any other frame.

In order to accomplish this I introduce a new function prop to carousel.js called `callback` which can be accessed downstream by a widget. In this way, any props on the carousel component can be fed into the callback and executed upstream.

### CODE REVIEW

**Comment by amio** [comment]
Sorry for the late response 😅

I think this can be done with widgets api & React's PureComponent:

```js
import React from "react";

export default class CallbackExample extends React.PureComponent {
  endCheck() {
    const { index, total } = this.props;
    if (index === total - 1) {
      console.log("We are at the end!");
    }
  }
  render() {
    this.endCheck();
    return null;
  }
}
```

I've made an [example on CodeSandbox](https://codesandbox.io/s/j22o38y3lv), is it meet your requirements?

**Comment by thevaleriemack** [comment]
> example on CodeSandbox

This doesn't not completely meet the requirement I have because I need to be able to pass the information back upstream to the parent component. That is why I introduce a new prop. However, I do think a pure component can be used. In the example you have, I need to modify it like so:

```
// callback-example.js

endCheck() {
// ...
this.props.callback("We are at the end");
}
```

Then in your file `index.js` I would execute the callback function and set state to the string provided to me.

So the data is going from Callback Widget -> Carousel -> App

**Comment by amio** [comment]
@thevaleriemack Is there some works you need to do in parent component other than the `endCheck()`?

**Comment by amio** [comment]
I made another example base on my understanding 😄, which enable a button by the end of slides:
https://codesandbox.io/s/q76q4k8woq

**Comment by amio** [comment]
I still not quite like the api surface. Going to close this PR for now,  appreciate for your advice and PR, and sorry for the long silence. @thevaleriemack

**Pull request closed without merging**
