### PR TITLE
OnclickMove Event for carousel

### PR DESCRIPTION
**Pull request by jawadakram20**

### CODE REVIEW

**Comment by jawadakram20** [comment]
@amio can you please delete my previous PR...and lets merge this one.

**Comment by amio** [comment]
Sure, I closed #25

**Comment by jawadakram20** [comment]
@amio Any issues in this?

**Comment by amio** [comment]
- It still conflicts with dragging behavior, adding this make dragging active wired.
- As this feature may not suitable for everyone, better to have a switch(eg. a `click-slide` prop) to enable it.

**Comment by jawadakram20** [comment]
@amio yes that would be great.Can you add that or should i do that

**Comment by amio** [comment]
It would be great if you can complete this PR,
If you don't have time, I may consider adding this sometimes, but I cannot guarantee when.

**Comment by jawadakram20** [comment]
ok i will add can you please give me command to run this locally.

**Comment by amio** [comment]
I've added it to [README](https://github.com/amio/re-carousel#contributes) in 224948da03b0a9c2aa2c90b2e46fd1cb59b91bdd

**Comment by jawadakram20** [comment]
Thanks

**Comment by travisdmathis** [comment]
Is this ever going to be merged in? This library is great, but needs a few things to really make it useable.. this is one of them. Would love to use this in my apps, but can't until these issues are resolved..

**Comment by amio** [comment]
I think this PR could get closed. Better to start a new PR to archive this.
Currently I'm working on something else, I'll take this later when I have more free time, meanwhile, any PR is welcome :)

**Pull request closed without merging**
